version: "3"

services:
  mongo1:
    image: mongo:6.0.10
    hostname: mongo1
    container_name: mongo1
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]
    networks:
      default:
        ipv4_address: 172.20.0.2
  mongo2:
    image: mongo:6.0.10
    hostname: mongo2
    container_name: mongo2
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]
    networks:
      default:
        ipv4_address: 172.20.0.3
  mongo3:
    image: mongo:6.0.10
    hostname: mongo3
    container_name: mongo3
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
    networks:
      default:
        ipv4_address: 172.20.0.4
  mongosetup:
    image: mongo:6.0.10
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    networks:
      default:
        ipv4_address: 172.20.0.6
  devicehub:
    container_name: devicehub
    build: .
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - MONGODB_PORT_27017_TCP=mongodb://172.20.0.2:27017
      - STF_ADMIN_EMAIL='test@example.com'
      - STF_ADMIN_NAME='test admin'
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip 0.0.0.0 --provider-min-port 7400 --provider-max-port 7500
    networks:
      default:
        ipv4_address: 172.20.0.5
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
