// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {deleteTeam} from '../../../controllers/teams.js'

export function del(req, res) {
    return deleteTeam(req, res)
}


