// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller silent-devices

import {getSilentDevice} from '../../../controllers/silent-devices.js'

export function get(req, res) {
    return getSilentDevice(req, res)
}


