// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller metrics

import {getMetrics} from '../controllers/metrics.js'

export function get(req, res) {
    return getMetrics(req, res)
}


