// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {createTeam} from '../controllers/teams.js'

export function post(req, res) {
    return createTeam(req, res)
}


