// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {getUsers, deleteUsers} from '../controllers/users.js'

export function get(req, res) {
    return getUsers(req, res, next)
}


export function del(req, res) {
    return deleteUsers(req, res, next)
}


