// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {getUserByEmail, createUser, deleteUser} from '../../controllers/users.js'

export function get(req, res) {
    return getUserByEmail(req, res, next)
}


export function post(req, res) {
    return createUser(req, res, next)
}


export function del(req, res) {
    return deleteUser(req, res, next)
}


