// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {removeUserFromTeam} from '../../../../controllers/teams.js'

export function del(req, res) {
    return removeUserFromTeam(req, res)
}


