// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {getUserTeams} from '../../../controllers/teams.js'

export function get(req, res) {
    return getUserTeams(req, res)
}


