// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller user

import {getUserDeviceBySerial, addUserDeviceV2, deleteUserDeviceBySerial} from '../../../controllers/user.js'

export function get(req, res) {
    return getUserDeviceBySerial(req, res, next)
}


export function post(req, res) {
    return addUserDeviceV2(req, res, next)
}


export function del(req, res) {
    return deleteUserDeviceBySerial(req, res, next)
}


