// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {addDeviceToOriginGroup, removeDeviceFromOriginGroup} from '../../../controllers/devices.js'

export function put(req, res) {
    return addDeviceToOriginGroup(req, res)
}


export function del(req, res) {
    return removeDeviceFromOriginGroup(req, res)
}


