// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller groups

import {getGroupDevice, addGroupDevice, removeGroupDevice} from '../../../../controllers/groups.js'

export function get(req, res) {
    return getGroupDevice(req, res, next)
}


export function put(req, res) {
    return addGroupDevice(req, res, next)
}


export function del(req, res) {
    return removeGroupDevice(req, res, next)
}


