// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller user

import {getUserAccessTokens, createAccessToken, deleteAccessTokens} from '../../controllers/user.js'

export function get(req, res) {
    return getUserAccessTokens(req, res, next)
}


export function post(req, res) {
    return createAccessToken(req, res, next)
}


export function del(req, res) {
    return deleteAccessTokens(req, res, next)
}


