// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {getDeviceBySerial, putDeviceBySerial, deleteDevice} from '../../controllers/devices.js'

export function get(req, res) {
    return getDeviceBySerial(req, res, next)
}


export function put(req, res) {
    return putDeviceBySerial(req, res, next)
}


export function del(req, res) {
    return deleteDevice(req, res, next)
}


