// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller users

import {getUserDevice, addUserDeviceV3, deleteUserDevice} from '../../../../controllers/users.js'

export function get(req, res) {
    return getUserDevice(req, res, next)
}


export function post(req, res) {
    return addUserDeviceV3(req, res, next)
}


export function del(req, res) {
    return deleteUserDevice(req, res, next)
}


