// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller devices

import {addOriginGroupDevice, removeOriginGroupDevice} from '../../../../controllers/devices.js'

export function put(req, res) {
    return addOriginGroupDevice(req, res, next)
}


export function del(req, res) {
    return removeOriginGroupDevice(req, res, next)
}


