// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {removeGroupFromTeam} from '../../../../controllers/teams.js'

export function del(req, res) {
    return removeGroupFromTeam(req, res)
}


