apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: devicehub-auth
  name: devicehub-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: devicehub-auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: devicehub-auth
    spec:
      containers:
        - args:
            - stf
            - auth-mock
            - --port
            - "3000"
            - --app-url
            - 'https://:'
            - --secret=
          envFrom:
            - configMapRef:
                name: scripts-variables-env
          image: vkcom/devicehub
          name: devicehub-auth
      restartPolicy: Always
