apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: devicehub-storage-plugin-image
  name: devicehub-storage-plugin-image
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: devicehub-storage-plugin-image
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: devicehub-storage-plugin-image
    spec:
      containers:
        - args:
            - stf
            - storage-plugin-image
            - --port
            - "3000"
            - --storage-url
            - https://:/
            - --secret=
          envFrom:
            - configMapRef:
                name: scripts-variables-env
          image: vkcom/devicehub
          name: devicehub-storage-plugin-image
      restartPolicy: Always
