apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: devicehub-triproxy-dev
  name: devicehub-triproxy-dev
spec:
  ports:
    - name: "7250"
      port: 7250
      targetPort: 7250
    - name: "7260"
      port: 7260
      targetPort: 7260
    - name: "7270"
      port: 7270
      targetPort: 7270
  selector:
    io.kompose.service: devicehub-triproxy-dev
