apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: devicehub-db-volume
  name: devicehub-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
