apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: devicehub-app
  name: devicehub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: devicehub-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: devicehub-app
    spec:
      containers:
        - args:
            - stf
            - app
            - --port
            - "3000"
            - --auth-url
            - https://:/
            - --websocket-url
            - https://:/
            - --secret=
          envFrom:
            - configMapRef:
                name: scripts-variables-env
          image: vkcom/devicehub
          name: devicehub-app
      restartPolicy: Always
