apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose-prod.yaml convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:bookworm
          name: devicehub-nginx
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-cm0
              readOnly: true
              subPath: nginx.conf
            - mountPath: /etc/nginx/ssl
              name: certs
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-cm0
          name: nginx-cm0
        - name: certs
          persistentVolumeClaim:
            claimName: certs
            readOnly: true
