// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller groups

import {getGroupDevices, addGroupDevices, removeGroupDevices} from '../../../controllers/groups.js'

export function get(req, res) {
    return getGroupDevices(req, res, next)
}


export function put(req, res) {
    return addGroupDevices(req, res, next)
}


export function del(req, res) {
    return removeGroupDevices(req, res, next)
}


