// Generated by /lib/units/api/gen_routes.py. DO NOT EDIT MANUALLY
// Generated for controller teams

import {getGroupsTeams} from '../../../controllers/teams.js'

export function get(req, res) {
    return getGroupsTeams(req, res)
}


