/**
 * Byte-exact replies to `reverse:` requests, as a real adbd would send them.
 *
 * We intercept `reverse:` on the tcpusb bridge and answer it ourselves, so these
 * bytes go straight into the user's `adb` client, which parses them with no
 * tolerance. Every format here is pinned to AOSP:
 *   - `SendProtocolString` (adb_io.cpp): 4 hex length chars + payload
 *   - `SendOkay` / `SendFail` (adb.cpp:1245, adb_io.cpp)
 *   - `handle_forward_request` (adb.cpp:1133) decides which of them is sent
 *
 * Note the `#if ADB_HOST` blocks in `handle_forward_request`: on a device those
 * are compiled out, so the device sends only ONE `OKAY` — the second one the
 * user sees is generated by their own server when our A_OKAY opens the stream.
 */

import type {ReverseCommand, ReverseForwards} from './forwards.ts'

/** 4 lowercase hex length chars followed by the payload (SendProtocolString). */
export function protocolString(s: string): Buffer {
    const payload = Buffer.from(s, 'utf8')
    const length = payload.length.toString(16).padStart(4, '0')
    return Buffer.concat([Buffer.from(length, 'ascii'), payload])
}

const OKAY = Buffer.from('OKAY', 'ascii')

/** "FAIL" followed by the reason as a protocol string (adb_io.cpp SendFail). */
export function fail(reason: string): Buffer {
    return Buffer.concat([Buffer.from('FAIL', 'ascii'), protocolString(reason)])
}

/**
 * One line per registered forward, exactly as AOSP `format_listeners()` writes
 * them: `<serial> <local-name> <remote-name>\n`. Entries created by
 * `adb reverse` have no serial, so the first column is the literal "(reverse)".
 *
 * Note the column order: `local_name` is the spec the listener binds on the
 * device (our `remote` key), and `connect_to` is where it forwards to (our
 * `local`).
 */
export function formatListeners(forwards: ReverseForwards): string {
    let result = ''
    for (const [remote, local] of forwards.entries()) {
        result += `(reverse) ${remote} ${local}\n`
    }
    return result
}

/**
 * The bytes a device sends back for a parsed `reverse:` command.
 *
 * `forwards` is only needed to answer `list-forward`; every other reply is a
 * fixed string. Anything we did not explicitly accept must come back as FAIL —
 * reporting OKAY for a request we refused would leave the user believing a
 * forward exists, and we would never open a stream for it.
 */
export function replyFor(command: ReverseCommand, forwards?: ReverseForwards): Buffer {
    switch (command.action) {
    case 'bind':
    case 'unbind':
    case 'unbind-all':
        return OKAY
    case 'list':
        // The only reply with no OKAY prefix: on a device the `#if ADB_HOST`
        // SendOkay above it is compiled out (adb.cpp:1137-1143).
        return protocolString(forwards ? formatListeners(forwards) : '')
    case 'bad-forward':
        // handle_forward_request recognises the `forward:` prefix and answers the
        // parse failure itself (adb.cpp:1190) instead of declining the command, so
        // this is NOT the "not a reverse forwarding command" fallback. The spec is
        // quoted with `forward:`/`norebind:` already stripped, because AOSP has
        // advanced its `service` pointer past them by then.
        return fail(`bad forward: ${command.spec}`)
    case 'bad-killforward':
        // Same ownership as bad-forward, different text: the check demands
        // exactly one non-empty piece, so a `;` in the spec lands here rather
        // than being read as a second argument (adb.cpp:1184).
        return fail(`bad killforward: ${command.spec}`)
    case 'rebind-refused':
        return fail('cannot rebind existing socket')
    case 'listener-not-found':
        return fail(`listener '${command.remote}' not found`)
    case 'unsupported':
        // A well-formed request we cannot serve is a bind failure, not a parse
        // failure — minirev can only listen on a TCP port.
        return fail('cannot bind listener: only tcp: specs are supported on this device')
    case 'unknown':
        // reverse_service's fallback when handle_forward_request declines the
        // command (daemon/services.cpp:69).
        return fail('not a reverse forwarding command')
    }
}
