name: build_checks.yaml
on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'

jobs:
  check_mac_os_build:
    runs-on: macos-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v4.2.2
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: build on MacOS
         run:
