name: Run Playwright Tests

on:
  pull_request:
    paths:
      - 'lib/**'
      - 'Dockerfile'
      - 'test/e2e/**'
      - 'docker-compose-e2e-tests.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'ui/**'
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Enable KVM
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm 
          
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script:  docker compose -f docker-compose-e2e-tests.yaml up --exit-code-from devicehub-e2e-tests --abort-on-container-exit devicehub-e2e-tests --remove-orphans

      - name: Show logs for devicehub
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml logs devicehub

      - name: Show logs for adb and emulator
        if: always()
        run: docker compose -f docker-compose-e2e-tests.yaml logs emulator