name: E2E Tests

on:
  pull_request:
    paths:
      - 'lib/**'
      - 'Dockerfile'
      - 'test/e2e/**'
      - 'docker-compose-e2e-tests.yaml'
      - 'package.json'
      - 'package-lock.json'
      - 'ui/**'
jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for emulator and devicehub
        run: |
          echo "⏳ Waiting 60s for emulator boot..."
          sleep 60
          docker-compose ps
          docker logs emulator || true

      - name: Run E2E tests
        run: docker-compose run --rm devicehub-e2e-tests

      - name: Logs on failure
        if: failure()
        run: |
          echo "=== Emulator Logs ==="
          docker logs emulator || true
          echo "=== DeviceHub Logs ==="
          docker logs devicehub || true

      - name: Shutdown
        if: always()
        run: docker-compose down
